# Generated by Django 3.0.5 on 2020-05-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('doctor', 'doctor'), ('patient', 'patient'), ('hr', 'hr'), ('receptionist', 'receptionist')], default=1, max_length=15),
        ),
    ]
