# Generated by Django 3.0.5 on 2020-05-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200524_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], default=1, max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('blood', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('AB-', 'AB-'), ('O-', 'O-'), ('O+', 'O+')], default=1, max_length=100)),
                ('med_reps', models.CharField(max_length=100)),
                ('case_paper', models.CharField(max_length=100)),
            ],
        ),
    ]
